/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WomenRouteImport } from './routes/women'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SeasonalRouteImport } from './routes/seasonal'
import { Route as MenRouteImport } from './routes/men'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as IndexRouteImport } from './routes/index'

const WomenRoute = WomenRouteImport.update({
  id: '/women',
  path: '/women',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonalRoute = SeasonalRouteImport.update({
  id: '/seasonal',
  path: '/seasonal',
  getParentRoute: () => rootRouteImport,
} as any)
const MenRoute = MenRouteImport.update({
  id: '/men',
  path: '/men',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/men': typeof MenRoute
  '/seasonal': typeof SeasonalRoute
  '/shop': typeof ShopRoute
  '/trending': typeof TrendingRoute
  '/women': typeof WomenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/men': typeof MenRoute
  '/seasonal': typeof SeasonalRoute
  '/shop': typeof ShopRoute
  '/trending': typeof TrendingRoute
  '/women': typeof WomenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/men': typeof MenRoute
  '/seasonal': typeof SeasonalRoute
  '/shop': typeof ShopRoute
  '/trending': typeof TrendingRoute
  '/women': typeof WomenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessories'
    | '/men'
    | '/seasonal'
    | '/shop'
    | '/trending'
    | '/women'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessories'
    | '/men'
    | '/seasonal'
    | '/shop'
    | '/trending'
    | '/women'
  id:
    | '__root__'
    | '/'
    | '/accessories'
    | '/men'
    | '/seasonal'
    | '/shop'
    | '/trending'
    | '/women'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessoriesRoute: typeof AccessoriesRoute
  MenRoute: typeof MenRoute
  SeasonalRoute: typeof SeasonalRoute
  ShopRoute: typeof ShopRoute
  TrendingRoute: typeof TrendingRoute
  WomenRoute: typeof WomenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/women': {
      id: '/women'
      path: '/women'
      fullPath: '/women'
      preLoaderRoute: typeof WomenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasonal': {
      id: '/seasonal'
      path: '/seasonal'
      fullPath: '/seasonal'
      preLoaderRoute: typeof SeasonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/men': {
      id: '/men'
      path: '/men'
      fullPath: '/men'
      preLoaderRoute: typeof MenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessoriesRoute: AccessoriesRoute,
  MenRoute: MenRoute,
  SeasonalRoute: SeasonalRoute,
  ShopRoute: ShopRoute,
  TrendingRoute: TrendingRoute,
  WomenRoute: WomenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
